package POJO;
// Generated 6 Oct, 2018 2:43:58 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Address generated by hbm2java
 */
public class Address  implements java.io.Serializable {


     private int id;
     private String streetName;
     private String cityName;
     private String stateName;
     private Integer zip;
     private Set employees = new HashSet(0);

    public Address() {
    }

	
    public Address(int id) {
        this.id = id;
    }
    public Address(int id, String streetName, String cityName, String stateName, Integer zip, Set employees) {
       this.id = id;
       this.streetName = streetName;
       this.cityName = cityName;
       this.stateName = stateName;
       this.zip = zip;
       this.employees = employees;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getStreetName() {
        return this.streetName;
    }
    
    public void setStreetName(String streetName) {
        this.streetName = streetName;
    }
    public String getCityName() {
        return this.cityName;
    }
    
    public void setCityName(String cityName) {
        this.cityName = cityName;
    }
    public String getStateName() {
        return this.stateName;
    }
    
    public void setStateName(String stateName) {
        this.stateName = stateName;
    }
    public Integer getZip() {
        return this.zip;
    }
    
    public void setZip(Integer zip) {
        this.zip = zip;
    }
    public Set getEmployees() {
        return this.employees;
    }
    
    public void setEmployees(Set employees) {
        this.employees = employees;
    }




}


