package POJO;
// Generated 6 Oct, 2018 2:43:58 PM by Hibernate Tools 3.6.0



/**
 * Employee generated by hbm2java
 */
public class Employee  implements java.io.Serializable {


     private Integer empId;
     private Address address;
     private String firstName;
     private String secondName;

    public Employee() {
    }

    public Employee(Address address, String firstName, String secondName) {
       this.address = address;
       this.firstName = firstName;
       this.secondName = secondName;
    }
   
    public Integer getEmpId() {
        return this.empId;
    }
    
    public void setEmpId(Integer empId) {
        this.empId = empId;
    }
    public Address getAddress() {
        return this.address;
    }
    
    public void setAddress(Address address) {
        this.address = address;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getSecondName() {
        return this.secondName;
    }
    
    public void setSecondName(String secondName) {
        this.secondName = secondName;
    }




}


